# Generated by Django 4.0.3 on 2022-03-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=32, null=True)),
                ('field2', models.CharField(blank=True, max_length=32, null=True)),
                ('field3', models.CharField(blank=True, max_length=32, null=True)),
                ('field4', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
